# Generated by Django 4.1.5 on 2023-01-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='curse',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_note',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='second_note',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='third_note',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
