# Generated by Django 4.1.5 on 2023-01-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_students_comments_alter_students_curse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='first_note',
            new_name='first_mark',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='second_note',
            new_name='second_mark',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='third_note',
            new_name='third_mark',
        ),
    ]
